services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - exclude:/app/node_modules/
    environment:
      - NODE_ENV=development

volumes:
  exclude:
